name: perf

on:
  push:
    branches: [main]
    paths-ignore: ['**/*.md']
  pull_request:
    branches: [main]
    paths-ignore: ['**/*.md']

jobs:
  perf:
    uses: HerrEmil/perf-config/.github/workflows/perf.yml@v1
    with:
      site_dir: build
      build_cmd: yarn build
      tier: spa
      package_manager: yarn
